http:
  listen_address: 0.0.0.0:8000

private_key_url: https://sdk.tellusxdp.com/api/manager/v1/auth/public_keys
counter_url: https://sdk.tellusxdp.com/api/manager/v1/items/counts

upstream: 
  url: https://www.sakura.ad.jp
  headers:
    X-Test-Header: hogetan

product_id: 9dc372e2-5819-4953-a696-5a599e760dc3
api_key: 7b4d73b1-425b-4082-897c-ba3c81962272
allowed_auth_types:
  - apikey
  - password
