listen_address: 0.0.0.0:8000

private_key_url: https://sdk.tellusxdp-staging.com/api/manager/v1/auth/public_keys
upstream: http://www.amemil.jp
provider_name: fukuyoshi-jiro
tool_label: weather-api
tool_id: 1_9ffc0bb13148c605795b5bc22143b7b00c30ad
