http:
  listen_address: 0.0.0.0:443
  tls:
    autocert:
      enabled: true
      cache_dir: /var/lib/gateway/autocert

private_key_url: https://sdk.tellusxdp.com/api/manager/v1/auth/public_keys
counter_url: https://sdk.tellusxdp.com/api/manager/v1/items/counts

upstream: 
  url: http://127.0.0.1:3000

product_id: 商品ID
api_key: 集計用APIキー
allowed_auth_types:
  - apikey
  - password
